apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
data:
  io.eldermael.ff.example.useNewBuild: "true"
  application.yaml: |
    io:
      eldermael:
        ff:
          example:
            useNewBuild: true
