repositories:
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx
    namespace: nginx
    chart: nginx/ingress-nginx

  - name: ff
    namespace: ff
    chart: ./ff